# Generated by Django 4.2 on 2023-08-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusConnect', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='local_government',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(default='Nigeria', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nin_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_of_origin',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
