# Generated by Django 4.2 on 2023-08-05 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusConnect', '0003_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='author',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='massage',
        ),
        migrations.AddField(
            model_name='complain',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complain',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
