# Generated by Django 4.2 on 2023-08-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusConnect', '0004_remove_complain_author_remove_complain_massage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
